version: '3'
services:
  api:
    image: jeffmay/rust_membership_api
    env_file:
      - .env
    links:
      - db
  db:
    image: "postgres:9.6"
    env_file:
      - .env
    ports:
      - "5432:5432"
